[platformio]
default_envs = d1mini_displaytest

[env:attiny84_via_ArduinoISP]
platform = atmelavr
board = attiny84
framework = arduino
upload_protocol = custom
upload_port = COM3
upload_speed = 19200
upload_flags =
  -C
  ${platformio.packages_dir}/tool-avrdude/avrdude.conf
  -p
  t84
  -P
  COM3
  -b
  19200
  -c
  stk500v1
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i
board_build.f_cpu = 8000000L
build_flags = -DCLOCK_SPEED=8000000UL
build_src_filter =
  -<*>
  +<firmware/>

[env:attiny84_set_fuses_8mhz]
platform = atmelavr
board = attiny84
upload_protocol = custom
upload_port = COM3
upload_speed = 19200
upload_flags =
  -C
  ${platformio.packages_dir}/tool-avrdude/avrdude.conf
  -p
  t84
  -P
  COM3
  -b
  19200
  -c
  stk500v1
upload_command = avrdude $UPLOAD_FLAGS -U lfuse:w:0xE2:m -U hfuse:w:0xDF:m -U efuse:w:0xFF:m

[env:d1mini_displaytest]
platform = espressif8266
board = d1_mini
framework = arduino
upload_protocol = esptool
upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
build_src_filter =
  -<*>
  +<displayclass/>
  +<displaytest/>